branch-defaults:
  master:
    environment: FoieJaune
global:
  application_name: FoieJaune
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
